export * from './productFilters';
export * from './currencies';
export * from './headers';

export const deliveryCountries = [
  { value: 'afghanistan', label: 'Afghanistan' },
  { value: 'australia', label: 'Australia' },
  { value: 'bahrain', label: 'Bahrain' },
  { value: 'bhutan', label: 'Bhutan' },
  { value: 'brazil', label: 'Brazil' },
  { value: 'canada', label: 'Canada' },
  { value: 'china', label: 'China' },
  { value: 'france', label: 'France' },
  { value: 'germany', label: 'Germany' },
  { value: 'india', label: 'India' },
  { value: 'indonesia', label: 'Indonesia' },
  { value: 'italy', label: 'Italy' },
  { value: 'japan', label: 'Japan' },
  { value: 'kuwait', label: 'Kuwait' },
  { value: 'malaysia', label: 'Malaysia' },
  { value: 'maldives', label: 'Maldives' },
  { value: 'nepal', label: 'Nepal' },
  { value: 'new_zealand', label: 'New Zealand' },
  { value: 'oman', label: 'Oman' },
  { value: 'pakistan', label: 'Pakistan' },
  { value: 'qatar', label: 'Qatar' },
  { value: 'russia', label: 'Russia' },
  { value: 'saudi_arabia', label: 'Saudi Arabia' },
  { value: 'singapore', label: 'Singapore' },
  { value: 'south_africa', label: 'South Africa' },
  { value: 'south_korea', label: 'South Korea' },
  { value: 'sri_lanka', label: 'Sri Lanka' },
  { value: 'thailand', label: 'Thailand' },
  { value: 'uae', label: 'United Arab Emirates' },
  { value: 'united_kingdom', label: 'United Kingdom' },
  { value: 'united_states', label: 'United States' },
];
